apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-api-chart.fullname" . }}
  labels:
    {{- include "crud-api-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crud-api-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        {{- include "crud-api-chart.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: "{{ .Chart.Name }}-init"
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: 
            - "job"
            - "{{ .Release.Name }}-crud-api-chart-{{ .Release.Revision}}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: crud-api-secret
                  key: DATABASE_URI
            - name: Logging__LogLevel__Default
              valueFrom:
                configMapKeyRef:
                  name: crud-api-config
                  key: Logging__LogLevel__Default