@startuml
'https://plantuml.com/sequence-diagram

actor "User"
participant "Nginx Api Gateway"
participant "Auth Api"
participant "Billing Api"
participant "Order Api"
participant "Notification Api"
participant "RabbitMQ"
participant "Postgres"

"User" -> "Auth Api" : Запрос POST /auth/login
"Auth Api" -> "User" : Новый JWT

"User" -> "Nginx Api Gateway" : Запрос POST /orders/idempotent\nHeaders: Idempotency-Key={GUID}
"Nginx Api Gateway" -> "Auth Api" : Проверка JWT
"Auth Api" -> "Nginx Api Gateway" : Авторизован - 200
"Nginx Api Gateway" -> "Order Api" : Запрос POST /orders/idempotent\nHeaders: Idempotency-Key={GUID}

alt #LightBlue Такого Idempotency-Key ещё нет

"Order Api" -> "Billing Api" : Снятие денег со счёта
"Billing Api" -> "Postgres" : Пессимистичная блокировка
"Postgres" -> "Billing Api" : Пессимистичная блокировка
"Billing Api" -> "Order Api" : Денег хватило
"Order Api" -> "Order Api" : Заказ создан
"Order Api" -> "RabbitMQ" : Отправка сообщения в очередь
"Order Api" -> "User" : Информация о заказе
"RabbitMQ" -> "Notification Api" : Обработка сообщения из очереди
"Notification Api" -> "User" : Отправка письма "счастья"

else #Pink Такой Idempotency-Key уже представлен и параметры заказа те же

"Order Api" -> "User" : Информация о существующем заказе

else #Red Такой Idempotency-Key уже представлен и параметры заказа изменены

"Order Api" -> "User" : 400 - дубликат Idempotency-Key

end

@enduml