{
 "title": "hw-3 dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Postgres version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{namespace=\"otus-project\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Postgres CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{namespace=\"otus-project\", service=\"db-postgresql-metrics\"}[5m]) * 1000)\n",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Postgres Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{namespace=\"otus-project\", service=\"db-postgresql-metrics\"}[5m]))\n",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{namespace=\"otus-project\", service=\"db-postgresql-metrics\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Postgres shared buffers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{namespace=\"otus-project\"}"
    }
   ]
  },
  {
   "title": "Postgres work mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{namespace=\"otus-project\"}"
    }
   ]
  },
  {
   "title": "RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (path) (rate(crud_api_http_requests_received_total[1m])) != 0",
     "legendFormat": "RPS {{path}}"
    }
   ]
  },
  {
   "title": "RPS by ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (exported_service) (rate(nginx_ingress_controller_requests[1m])) != 0",
     "legendFormat": "RPS {{exported_service}}"
    }
   ]
  },
  {
   "title": "Latency by endpoint (0.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, path) \n         (rate(crud_api_http_request_duration_seconds_bucket[1m])) != 0\n) * 1000\n",
     "legendFormat": "{{path}} latency, ms"
    }
   ]
  },
  {
   "title": "Latency by ingress (0.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_service) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) != 0\n) * 1000\n",
     "legendFormat": "{{exported_service}} latency, ms"
    }
   ]
  },
  {
   "title": "Latency by endpoint (0.95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, path) \n         (rate(crud_api_http_request_duration_seconds_bucket[1m])) != 0\n) * 1000\n",
     "legendFormat": "{{path}} latency, ms"
    }
   ]
  },
  {
   "title": "Latency by ingress (0.95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_service) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) != 0\n) * 1000\n",
     "legendFormat": "{{exported_service}} latency, ms"
    }
   ]
  },
  {
   "title": "Latency by endpoint (0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, path) \n         (rate(crud_api_http_request_duration_seconds_bucket[1m])) != 0\n) * 1000\n",
     "legendFormat": "{{path}} latency, ms"
    }
   ]
  },
  {
   "title": "Latency by ingress (0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_service) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) != 0\n) * 1000\n",
     "legendFormat": "{{exported_service}} latency, ms"
    }
   ]
  },
  {
   "title": "Latency by endpoint (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, path) \n         (rate(crud_api_http_request_duration_seconds_bucket[1m])) != 0\n) * 1000\n",
     "legendFormat": "{{path}} latency, ms"
    }
   ]
  },
  {
   "title": "Latency by ingress (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, exported_service) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) != 0\n) * 1000\n",
     "legendFormat": "{{exported_service}} latency, ms"
    }
   ]
  },
  {
   "title": "CPU usage by pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"otus-project\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"otus-project\", workload=\"crud-api-crud-api-chart\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage by pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"otus-project\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"otus-project\", workload=\"crud-api-crud-api-chart\", workload_type=\"deployment\"}\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error rate by app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (code) (increase(crud_api_http_requests_received_total{code=~\"5.+\", path!=\"\"}[1m])) != 0",
     "legendFormat": "Error code {{code}}"
    }
   ]
  },
  {
   "title": "Error rate by ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m])) != 0",
     "legendFormat": "Error code {{status}}"
    }
   ]
  }
 ]
}