prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

prometheus-node-exporter:
  hostRootFsMount: false

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana-dashboard