apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "crud-api-chart.fullname" . }}-{{ .Release.Revision }}
  labels: {{- include "crud-api-chart.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels: {{- include "crud-api-chart.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        command: ["dotnet"]
        args: ["Otus.Project.CrudApi.dll", "migrate=true"]
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: crud-api-secret
                key: DATABASE_URI