apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-api-config
data:
  Logging__LogLevel__Default: Warning
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-api-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "Server=%s;Port=%s;Database=%s;User Id=%s;Pwd=%s;" .Values.externalPostgresql.postgresqlHost .Values.externalPostgresql.postgresqlPort .Values.externalPostgresql.postgresqlDatabase .Values.externalPostgresql.postgresqlUsername .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
